title: "2nfree's Blog"
subtitle: ""
description: ""
keywords:
author: 2nfree
language: zh-CN
timezone: "Asia/Shanghai"

#CDN配置
jsdelivr_cdn:
  use_cdn: true 
  deploy_when_generating: false
  cdn_url_prefix: https://cdn.jsdelivr.net/gh/2nfree/2nfree-blog-static/
  git_repo_url: git@github.com:2nfree/2nfree-blog-static.git
#   token:
  asset_dirs:
    - static/images

url: https://blog.2nfree.com

permalink: :year/:month/:day/:title/ # 文章的永久链接格式
permalink_defaults: # 永久链接中各部分的默认值
pretty_urls: # 改写 permalink 的值来美化 URL
  trailing_index: false # 是否在永久链接中保留尾部的 index.html，设置为 false 时去除
  trailing_html: true # 是否在永久链接中保留尾部的 .html, 设置为 false 时去除 (对尾部的 index.html无效)

source_dir: source # 资源文件夹，这个文件夹用来存放内容
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # Include code 文件夹，source_dir 下的子目录
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render: # 跳过指定文件的渲染。

new_post_name: :year-:month-:day-:title.md # 新文章的文件名称
default_layout: post # 预设布局
auto_spacing: true # 在中文和英文之间加入空格
titlecase: false # 把标题转换为 title case
external_link: # 在新标签中打开链接
  enable: true
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: "" # 需要排除的域名。主域名和子域名如 www 需分别配置
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: true # 启动 Asset 文件夹
relative_link: false # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
highlight: # 代码块的设置, 请参考 Highlight.js 进行设置
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs: # 代码块的设置, 请参考 PrismJS 进行设置
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

index_generator:
  path: ""
  per_page: 10
  order_by: -date

default_category: uncategorized # 默认分类
category_map: # 分类别名
tag_map: # 标签别名

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime" # 当 Front Matter 中没有指定 updated 时 updated 的取值

per_page: 10 # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录

# 设置 include/exclude 可以让 Hexo 进行处理或忽略某些目录和文件夹
# include:
# exclude:
# ignore:

#样式
theme: redefine

#部署配置
deploy:
  - type: "git"
    repo: "git@github.com:2nfree/2nfree.github.io.git"
    branch: master

#添加RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20